# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/vivid64"
  config.vm.box_url = "file:///C://ubuntu-vivid64.box"
  config.vm.hostname = "pubean"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 5432, host: 5050
  # config.vm.network "private_network", ip: "192.168.1.110"
  # config.vm.network "public_network", ip: "192.168.1.110"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "pubean"
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.provision :shell, path: "bootstrap.sh"

end
