export ZSH=$HOME/.oh-my-zsh

# Alias Definition
alias ll="ls -lh"
alias la="ls -lha"
alias cls="clear"
alias ..="cd .."
alias ...="cd ../.."
alias du="du -sh *"
alias da="du -sh .* *"
alias fd="find . -type d -name"
alias ff="find . -type f -name"
alias t="xtail -f"
alias pep8="autopep8 --in-place --aggressive --aggressive"
alias pup="pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs pip install -U"
alias vi="vim"
alias ed="subl ."
alias grep="grep --color"
alias bower="noglob bower"
alias npm="npm --no-bin-links"
alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"
alias zips="unzip -O CP936"
alias -s gz="tar -xzvf"
alias -s tgz="tar -xzvf"
alias -s bz2="tar -xjvf"
alias -s zip="unzip"

HIST_STAMPS="yyyy-mm-dd"
ZSH_THEME="kennethreitz"

# Plugin Tuple
plugins=(adb autojump autopep8 bower brew cp debian django docker emoji emoji-clock encode64
extract fabric git-extras git-flow git github gitignore gulp httpie iwhois jsontoolsnode npm
nvm osx pep8 pip python sublime sudo ubuntu vagrant virtualenv virtualenvwrapper vundle
web-search xcode zsh_reload)

source $ZSH/oh-my-zsh.sh

# User Configuration
